### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by sank2000** [benxene/7days-50projects#135]
Status: 500

This Serverless Function has crashed.

![Capture](https://user-images.githubusercontent.com/51191409/123120567-0d4d8600-d462-11eb-9269-b1e6af4e7b0a.PNG)

**Comment by KrishnaMoorthy12** [comment]
Weird, works for me:
![image](https://user-images.githubusercontent.com/41967554/123121696-03785280-d463-11eb-8bd3-7efa9b0fadee.png)

> Status: 500
> 
> This Serverless Function has crashed.

**Comment by KrishnaMoorthy12** [comment]
Works fine, I've upstreamed anyway. Reopen if the problem persists.
